frontend:
    build: nginx/
    ports: 
        - "80:80" 
        - "443:443"
    links:
        - "backend"
    restart: always
    volumes: 
        - datasius_static_vol:/srv/datasius/static_root
        - datasius_db_vol:/srv/sqlitedir
        - datasius_assets_vol:/srv/datasius/assets
backend: 
    build: website/ 
    ports:
        - "8001:8001"
    restart: always
    volumes: 
       - datasius_static_vol:/srv/datasius/static_root
       - datasius_db_vol:/srv/datasius/data/sqlitedir
       - datasius_assets_vol:/srv/datasius/assets
